/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SuhailRouteImport } from './routes/suhail'
import { Route as SubjectsRouteImport } from './routes/subjects'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsIndexRouteImport } from './routes/subjects.index'
import { Route as SubjectsSlugRouteImport } from './routes/subjects.$slug'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiSuhailRouteImport } from './routes/api/suhail'
import { Route as ApiSpeakRouteImport } from './routes/api/speak'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as TopicSubjectUnitTopicRouteImport } from './routes/topic.$subject.$unit.$topic'

const SuhailRoute = SuhailRouteImport.update({
  id: '/suhail',
  path: '/suhail',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsRoute = SubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsIndexRoute = SubjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsRoute,
} as any)
const SubjectsSlugRoute = SubjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SubjectsRoute,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSuhailRoute = ApiSuhailRouteImport.update({
  id: '/api/suhail',
  path: '/api/suhail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSpeakRoute = ApiSpeakRouteImport.update({
  id: '/api/speak',
  path: '/api/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicSubjectUnitTopicRoute = TopicSubjectUnitTopicRouteImport.update({
  id: '/topic/$subject/$unit/$topic',
  path: '/topic/$subject/$unit/$topic',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/suhail': typeof SuhailRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/suhail': typeof ApiSuhailRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/topic/$subject/$unit/$topic': typeof TopicSubjectUnitTopicRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/suhail': typeof SuhailRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/suhail': typeof ApiSuhailRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/subjects': typeof SubjectsIndexRoute
  '/topic/$subject/$unit/$topic': typeof TopicSubjectUnitTopicRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/subjects': typeof SubjectsRouteWithChildren
  '/suhail': typeof SuhailRoute
  '/api/chat': typeof ApiChatRoute
  '/api/speak': typeof ApiSpeakRoute
  '/api/suhail': typeof ApiSuhailRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/subjects/$slug': typeof SubjectsSlugRoute
  '/subjects/': typeof SubjectsIndexRoute
  '/topic/$subject/$unit/$topic': typeof TopicSubjectUnitTopicRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/subjects'
    | '/suhail'
    | '/api/chat'
    | '/api/speak'
    | '/api/suhail'
    | '/api/transcribe'
    | '/subjects/$slug'
    | '/subjects/'
    | '/topic/$subject/$unit/$topic'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/suhail'
    | '/api/chat'
    | '/api/speak'
    | '/api/suhail'
    | '/api/transcribe'
    | '/subjects/$slug'
    | '/subjects'
    | '/topic/$subject/$unit/$topic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/chat'
    | '/subjects'
    | '/suhail'
    | '/api/chat'
    | '/api/speak'
    | '/api/suhail'
    | '/api/transcribe'
    | '/subjects/$slug'
    | '/subjects/'
    | '/topic/$subject/$unit/$topic'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  SubjectsRoute: typeof SubjectsRouteWithChildren
  SuhailRoute: typeof SuhailRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiSpeakRoute: typeof ApiSpeakRoute
  ApiSuhailRoute: typeof ApiSuhailRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  TopicSubjectUnitTopicRoute: typeof TopicSubjectUnitTopicRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/suhail': {
      id: '/suhail'
      path: '/suhail'
      fullPath: '/suhail'
      preLoaderRoute: typeof SuhailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects': {
      id: '/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof SubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/': {
      id: '/subjects/'
      path: '/'
      fullPath: '/subjects/'
      preLoaderRoute: typeof SubjectsIndexRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/subjects/$slug': {
      id: '/subjects/$slug'
      path: '/$slug'
      fullPath: '/subjects/$slug'
      preLoaderRoute: typeof SubjectsSlugRouteImport
      parentRoute: typeof SubjectsRoute
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/suhail': {
      id: '/api/suhail'
      path: '/api/suhail'
      fullPath: '/api/suhail'
      preLoaderRoute: typeof ApiSuhailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/speak': {
      id: '/api/speak'
      path: '/api/speak'
      fullPath: '/api/speak'
      preLoaderRoute: typeof ApiSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topic/$subject/$unit/$topic': {
      id: '/topic/$subject/$unit/$topic'
      path: '/topic/$subject/$unit/$topic'
      fullPath: '/topic/$subject/$unit/$topic'
      preLoaderRoute: typeof TopicSubjectUnitTopicRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SubjectsRouteChildren {
  SubjectsSlugRoute: typeof SubjectsSlugRoute
  SubjectsIndexRoute: typeof SubjectsIndexRoute
}

const SubjectsRouteChildren: SubjectsRouteChildren = {
  SubjectsSlugRoute: SubjectsSlugRoute,
  SubjectsIndexRoute: SubjectsIndexRoute,
}

const SubjectsRouteWithChildren = SubjectsRoute._addFileChildren(
  SubjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  SubjectsRoute: SubjectsRouteWithChildren,
  SuhailRoute: SuhailRoute,
  ApiChatRoute: ApiChatRoute,
  ApiSpeakRoute: ApiSpeakRoute,
  ApiSuhailRoute: ApiSuhailRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  TopicSubjectUnitTopicRoute: TopicSubjectUnitTopicRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
